apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  labels: {}
spec:
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - image: telegraf:1.27.4
        imagePullPolicy: IfNotPresent
        name: telegraf
        envFrom:
        - secretRef:
            name: telegraf-env
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TZ
          value: Europe/Prague
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: config
          subPath: telegraf.conf
          readOnly: true
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: telegraf-config
