apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - image: telegraf:1.36.2
        imagePullPolicy: IfNotPresent
        name: telegraf
        envFrom:
        - secretRef:
            name: telegraf-env
        args:
          - "--unprotected"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: config
          subPath: telegraf.conf
          readOnly: true
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_RAW
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: telegraf-config
